# Safely loading optimizer state from a self-generated, trusted
# checkpoint file.
sonar.issue.ignore.multicriteria.torchload.ruleKey=python:S6985
sonar.issue.ignore.multicriteria.torchload.resourceKey=**/*.py
# no crypto security needed
sonar.issue.ignore.multicriteria.random.ruleKey=cpp:S2245
sonar.issue.ignore.multicriteria.random.resourceKey=**/*.{cpp,h}